[package]
name = "near-bigdecimal"
version = "0.1.1"
authors = ["dongcool"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/linear-protocol/near-bigdecimal.git"
description = """
Big decimal for NEAR smart contracts
"""
keywords = ["bigdecimal"]
edition = "2018"

[dependencies]
uint = { version = "0.9.3", default-features = false }
near-sdk = "4.1.1"

[dev-dependencies]
rand = "0.8"
